---
extends:
  - react-app
  - eslint:recommended
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings

plugins:
  - jsx-a11y
  - react
  - import

env:
  browser: true
  jest: true
  es6: true
  jquery: true

parserOptions:
  ecmaFeatures:
    jsx: true

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
      moduleDirectory:
        - src
        - node_modules

rules:
  max-len:
    - error
    - code: 120
  semi:
    - error
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - before: false
      after: true
  quotes:
    - error
    - single
    - avoidEscape: true
  camelcase:
    - error
  keyword-spacing:
    - error
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 0
  arrow-spacing:
    - error
    - before: true
      after: true
  import/order:
    - error
    - newlines-between: always
  import/named:
    - off
  jsx-a11y/no-static-element-interactions:
    - off
  jsx-a11y/click-events-have-key-events:
    - off
  arrow-body-style:
    - error
    - as-needed
  no-trailing-spaces:
    - error
    - ignoreComments: true
